import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { CTA, PageHero, SectionHeading, SiteShell, techStack } from '@/components/site'
import { pageMetadata } from '@/lib/metadata'

const data: Record<string,{title:string;copy:string;eyebrow:string;items:string[];sections:[string,string][]}> = {
 'ai-automation': { title:'Turn repetitive operations into intelligent systems.', copy:'Design practical AI systems that help teams understand information, make decisions, and move work forward—with clear human oversight and production-minded engineering.', eyebrow:'AI & AGENTIC AUTOMATION', items:['AI agents','LLM integrations','RAG systems','AI copilots','Workflow automation','Document intelligence','Internal AI tools','Business process automation'], sections:[['What we build','Agents, copilots, retrieval systems, document workflows, and AI features that fit the way your team already works.'],['How it works','We map the workflow, define where intelligence helps, prototype the interaction, then build a reliable path to production.'],['Security considerations','We design around permissions, data boundaries, evaluation, observability, and human review rather than treating an LLM as a black box.']]},
 'software-engineering': { title:"Software engineered for today—and designed for what&apos;s next.",copy:'Build durable digital products with a team that can think across product, frontend, backend, integrations, testing, and deployment.',eyebrow:'SOFTWARE ENGINEERING',items:['SaaS platforms','Web applications','Backend systems','APIs','Enterprise systems','Third-party integrations','Modernization','Testing & DevOps'],sections:[['A full product view','We connect product intent to technical decisions so the system stays useful after the first release.'],['Capabilities, not logo walls','React, Next.js, TypeScript, Node.js, Python, PostgreSQL, MongoDB, Redis, AWS, and Docker are tools we apply when they fit.'],['Built for change','Clear boundaries, testing, documentation, and deployment practices make the next iteration easier.']]},
 mobile:{title:'Mobile products people actually want to use.',copy:'Create focused, reliable mobile experiences that connect cleanly to the systems behind them and stay maintainable as the product grows.',eyebrow:'MOBILE ENGINEERING',items:['React Native','Flutter','iOS','Android','API integration','Authentication','Payments','Push notifications','Analytics','App deployment'],sections:[['Experience and systems','We design the mobile surface and the APIs, auth, payments, notifications, and analytics it depends on.'],['Cross-platform where it helps','React Native and Flutter can create speed and consistency; native technologies remain available when the product needs them.'],['Release with confidence','Testing, observability, and store deployment are part of shipping—not an afterthought.']]},
 'cloud-devops':{title:'Infrastructure that keeps your product moving.',copy:'Bring engineering and infrastructure together with secure delivery pipelines, observable systems, and cloud architecture built around the product.',eyebrow:'CLOUD & DEVOPS',items:['AWS','Azure','Docker','CI/CD','Infrastructure automation','Monitoring','Security','Scaling','Deployment'],sections:[['Delivery as a capability','Automated testing and deployment reduce friction between a finished change and a useful release.'],['Operational clarity','Monitoring, logging, and clear runbooks help teams understand systems in production.'],['Scale deliberately','We choose the simplest infrastructure that meets current needs and leaves a clear path forward.']]}
}
export async function generateStaticParams(){return Object.keys(data).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=data[slug];return pageMetadata(item?.title?.replace('&apos;',"'")||'Solutions','VectorShip solution capabilities and engineering services.','/solutions/'+slug)}
export default async function SolutionDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=data[slug]||data['software-engineering'];return <SiteShell><main><PageHero eyebrow={item.eyebrow} title={item.title.replace('&apos;',"'")} copy={item.copy}><Link href="/contact" className="card-link">Discuss this capability <ArrowUpRight className="size-4" /></Link></PageHero><section className="section shell"><SectionHeading eyebrow="CAPABILITIES" title="A practical toolkit for the work ahead."/><div className="tag-list large-tags mt-10">{item.items.map(i=><span key={i}>{i}</span>)}</div><div className="detail-sections mt-20">{item.sections.map(([title,copy])=><article key={title}><p className="eyebrow">{title}</p><p>{copy}</p></article>)}</div></section><CTA title="Ready to explore the opportunity?" copy="Bring us the problem. We will help you find the right technical path."/></main></SiteShell>}
